export const cuisineList = [
  "Beastial",
  "Fleshborne",
  "Bloodborne",
  "Nibbles",
  "Celestial",
  "Shadowroot",
  "Eldritch",
  "Mystic",
  "Arcane",
  "Infernal",
  "Cursed",
  "Draconic",
  "Abyssal",
  "Spectral",
  "Haunted",
  "Necrotic",
  "Wraithfare",
  "Phantasmal",
  "Lich",
  "Revenant",
  "Forbidden",
  "Vampire",
  "Vittles",
  "Enchanted",
  "Hexed",
  "Twilight",
  "DoomDew",
  "Fiendish",
  "Delights",
  "Darkling",
  "NightDew",
  "Elixir",
  "Spellbound",
  "Moonshine",
  "Blood Salads",
  "Soul Snacks",
  "DragonBreath BBQ",
  "Witch's Brew",
  "Sorcerer's Stew",
  "BloodySweets",
  "Rotten Brains",
  "Blood",
];
